/* ============================================================
   data.js — all lesson content & exercise data
   12 lessons across 4 difficulty tiers, 7 exercises each.
   Exercise types: BUILD (3), SELECT (2), MATCH (2) per lesson.
   ============================================================ */

const TIERS = [
  { tier: 1, name: 'Tier 1 · Beginnings',  reqXp: 0 },
  { tier: 2, name: 'Tier 2 · Everyday',    reqXp: 40 },
  { tier: 3, name: 'Tier 3 · Out & About', reqXp: 100 },
  { tier: 4, name: 'Tier 4 · Expression',  reqXp: 200 },
];

const LESSONS = [
  /* ───────────── TIER 1 ───────────── */
  {
    id: 'first-words', tier: 1, reqXp: 0, name: 'First Words', emoji: '✨',
    exercises: [
      /* 1 · RULE — name the rule, show examples, then test understanding */
      { type: 'RULE',
        rule: 'Nepali sentence order is <strong>Subject → Object → Verb</strong>. The verb always comes <strong>last</strong> — the opposite of English, where the verb sits in the middle.',
        examples: [
          'म भात खान्छु — literally “I rice eat” = I eat rice',
          'म पानी पिउँछु — literally “I water drink” = I drink water',
          'ऊ किताब पढ्छ — literally “He book reads” = He reads a book',
        ],
        instruction: 'Based on the rule, answer:',
        question: 'In a Nepali sentence, where does the verb go?',
        options: ['At the very end', 'At the very start', 'Right after the subject', 'Anywhere you like'],
        answer: 'At the very end',
        explanation: 'Correct — Nepali is Subject–Object–Verb, so the verb always comes last.' },
      /* 2 · ARRANGE — apply the structure you just learned */
      { type: 'BUILD', instruction: 'Arrange in Subject–Object–Verb order', english: 'I drink water',
        answer: ['म', 'पानी', 'पिउँछु'], wordBank: ['म', 'पानी', 'पिउँछु', 'भात'],
        translation: 'म पानी पिउँछु — I drink water (literally “I water drink”)' },
      /* 3 · SCRIPT — Devanagari recognition, no typing */
      { type: 'SCRIPT', instruction: 'Which sound does this letter make?', prompt: 'म',
        options: ['ma', 'pa', 'ka', 'la'], answer: 'ma',
        explanation: 'म is “ma” — the first sound in म (ma, “I”) and मेरो (mero, “my”).' },
      /* 4 · MCQ — recognition */
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'नमस्ते',
        options: ['Hello / Greetings', 'Thank you', 'Water', 'Yes'], answer: 'Hello / Greetings',
        translation: 'नमस्ते — a greeting for both hello and goodbye' },
      /* 5 · FILL — production (type it yourself) */
      { type: 'FILL', instruction: 'Type the answer (Devanagari or romanized)',
        prompt: '“Thank you” in Nepali is _____', english: 'Hint: starts with “dhanya…”',
        acceptedAnswers: ['धन्यवाद', 'dhanyabad', 'dhanyabaad', 'dhanyawad', 'dhanyavad'],
        explanation: 'धन्यवाद · dhanyabad — Thank you.' },
    ],
  },
  {
    id: 'greetings', tier: 1, reqXp: 0, name: 'Greetings', emoji: '👋',
    exercises: [
      { type: 'RULE',
        rule: 'Nepali has <strong>no separate word for “goodbye”</strong>. <strong>नमस्ते (namaste)</strong> covers both hello and goodbye, said with palms pressed together.',
        examples: [
          'नमस्ते — said when you arrive (hello)',
          'नमस्ते — said again when you leave (goodbye)',
          'For extra respect to elders: नमस्कार (namaskār)',
        ],
        instruction: 'Based on the rule, answer:',
        question: 'When can you say नमस्ते?',
        options: ['Both arriving and leaving', 'Only when arriving', 'Only when leaving', 'Only to say thanks'],
        answer: 'Both arriving and leaving',
        explanation: 'Right — नमस्ते works for both hello and goodbye.' },
      { type: 'BUILD', instruction: 'Build the question', english: 'How are you?',
        answer: ['तपाईंलाई', 'कस्तो', 'छ'], wordBank: ['तपाईंलाई', 'कस्तो', 'छ', 'म'], translation: 'तपाईंलाई कस्तो छ? — How are you?' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'सुप्रभात',
        options: ['Good night', 'Good morning', 'Welcome', 'Goodbye'], answer: 'Good morning',
        translation: 'सुप्रभात — Good morning' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मेरो नाम राम _____',
        english: 'My name is Ram', answer: 'हो', options: ['हो', 'छ', 'पानी', 'नाम'],
        translation: 'मेरो नाम राम हो — My name is Ram' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'I am fine',
        answer: ['मलाई', 'सञ्चै', 'छ'], wordBank: ['मलाई', 'सञ्चै', 'छ', 'तपाईं'], translation: 'मलाई सञ्चै छ — I am fine' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'स्वागत _____',
        english: 'Welcome', answer: 'छ', options: ['छ', 'हो', 'म', 'नाम'],
        translation: 'स्वागत छ — Welcome' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'हजुर',
        options: ['Excuse me / Yes', 'Water', 'No', 'Tea'], answer: 'Excuse me / Yes',
        translation: 'हजुर — a polite "yes" or "excuse me"' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'See you tomorrow',
        answer: ['भोलि', 'भेटौंला'], wordBank: ['भोलि', 'भेटौंला', 'हिजो'], translation: 'भोलि भेटौंला — See you tomorrow' },
      { type: 'FILL', instruction: 'Type the answer (Devanagari or romanized)',
        prompt: '“Good morning” in Nepali is _____', english: 'Hint: starts with “su…”',
        acceptedAnswers: ['सुप्रभात', 'suprabhat', 'suprabhaat'],
        explanation: 'सुप्रभात · suprabhat — Good morning.' },
    ],
  },
  {
    id: 'numbers', tier: 1, reqXp: 0, name: 'Numbers 1–10', emoji: '🔢',
    exercises: [
      { type: 'RULE',
        rule: 'Nepali uses its own <strong>Devanagari digits</strong>: १ २ ३ ४ ५ = 1 2 3 4 5. In speech the words are <strong>एक, दुई, तीन</strong> (ek, dui, teen).',
        examples: ['१ = एक (ek) = one', '२ = दुई (dui) = two', '५ = पाँच (pā̃ch) = five'],
        instruction: 'Based on the rule, answer:',
        question: 'Which Devanagari digit means “one”?',
        options: ['१', '२', '३', '०'],
        answer: '१',
        explanation: '१ is the digit for one; the spoken word is एक (ek).' },
      { type: 'MATCH', instruction: 'What number is this?', prompt: 'एक',
        options: ['One', 'Two', 'Ten', 'Five'], answer: 'One', translation: 'एक — One (1)' },
      { type: 'MATCH', instruction: 'What number is this?', prompt: 'पाँच',
        options: ['Three', 'Four', 'Five', 'Nine'], answer: 'Five', translation: 'पाँच — Five (5)' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मसँग _____ रुपैयाँ छ',
        english: 'I have ten rupees', answer: 'दश', options: ['दश', 'हो', 'पानी', 'ठूलो'],
        translation: 'मसँग दश रुपैयाँ छ — I have ten rupees' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'Two cups of tea',
        answer: ['दुई', 'कप', 'चिया'], wordBank: ['दुई', 'कप', 'चिया', 'तीन'], translation: 'दुई कप चिया — Two cups of tea' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I have three brothers',
        answer: ['मेरा', 'तीन', 'दाइ', 'छन्'], wordBank: ['मेरा', 'तीन', 'दाइ', 'छन्', 'दुई'], translation: 'मेरा तीन दाइ छन् — I have three brothers' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'उसँग _____ किताब छन्',
        english: 'He has four books', answer: 'चार', options: ['चार', 'नौ', 'हो', 'रातो'],
        translation: 'उसँग चार किताब छन् — He has four books' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'Give me one',
        answer: ['मलाई', 'एक', 'दिनुहोस्'], wordBank: ['मलाई', 'एक', 'दिनुहोस्', 'दुई'], translation: 'मलाई एक दिनुहोस् — Give me one' },
    ],
  },

  /* ───────────── TIER 2 ───────────── */
  {
    id: 'family', tier: 2, reqXp: 40, name: 'My Family', emoji: '👪',
    exercises: [
      { type: 'BUILD', instruction: 'Build the sentence', english: 'This is my mother',
        answer: ['यो', 'मेरी', 'आमा', 'हो'], wordBank: ['यो', 'मेरी', 'आमा', 'हो', 'बुवा'], translation: 'यो मेरी आमा हो — This is my mother' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'बुवा',
        options: ['Father', 'Mother', 'Sister', 'Brother'], answer: 'Father', translation: 'बुवा — Father' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मेरी _____ ठूली हुनुहुन्छ',
        english: 'My older sister is older', answer: 'दिदी', options: ['दिदी', 'दाइ', 'आमा', 'भाइ'],
        translation: 'मेरी दिदी ठूली हुनुहुन्छ — My older sister is older' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'My family is big',
        answer: ['मेरो', 'परिवार', 'ठूलो', 'छ'], wordBank: ['मेरो', 'परिवार', 'ठूलो', 'छ', 'सानो'], translation: 'मेरो परिवार ठूलो छ — My family is big' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मेरो _____ हुनुहुन्छ',
        english: 'My father', answer: 'बुवा', options: ['बुवा', 'दिदी', 'भाइ', 'नाम'],
        translation: 'मेरो बुवा हुनुहुन्छ — This is my father' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'दिदी',
        options: ['Older sister', 'Younger brother', 'Mother', 'Aunt'], answer: 'Older sister', translation: 'दिदी — Older sister' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I love my family',
        answer: ['म', 'मेरो', 'परिवारलाई', 'माया', 'गर्छु'], wordBank: ['म', 'मेरो', 'परिवारलाई', 'माया', 'गर्छु', 'छ'], translation: 'म मेरो परिवारलाई माया गर्छु — I love my family' },
    ],
  },
  {
    id: 'home', tier: 2, reqXp: 40, name: 'My Home', emoji: '🏠',
    exercises: [
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'घर',
        options: ['House / Home', 'School', 'Market', 'River'], answer: 'House / Home', translation: 'घर — House / Home' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'This is my house',
        answer: ['यो', 'मेरो', 'घर', 'हो'], wordBank: ['यो', 'मेरो', 'घर', 'हो', 'ठूलो'], translation: 'यो मेरो घर हो — This is my house' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'म _____ मा छु',
        english: 'I am at home', answer: 'घर', options: ['घर', 'रेल', 'बजार', 'पानी'],
        translation: 'म घरमा छु — I am at home' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'The door is open',
        answer: ['ढोका', 'खुला', 'छ'], wordBank: ['ढोका', 'खुला', 'छ', 'बन्द'], translation: 'ढोका खुला छ — The door is open' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'कोठा _____ छ',
        english: 'The room is clean', answer: 'सफा', options: ['सफा', 'फोहोर', 'रातो', 'ठूलो'],
        translation: 'कोठा सफा छ — The room is clean' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'कोठा',
        options: ['Room', 'Roof', 'Window', 'Kitchen'], answer: 'Room', translation: 'कोठा — Room' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'My home is beautiful',
        answer: ['मेरो', 'घर', 'राम्रो', 'छ'], wordBank: ['मेरो', 'घर', 'राम्रो', 'छ', 'सानो'], translation: 'मेरो घर राम्रो छ — My home is beautiful' },
    ],
  },
  {
    id: 'food', tier: 2, reqXp: 40, name: 'Food & Drink', emoji: '🍲',
    exercises: [
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I eat rice',
        answer: ['म', 'भात', 'खान्छु'], wordBank: ['म', 'भात', 'खान्छु', 'पिउँछु'], translation: 'म भात खान्छु — I eat rice' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'पानी',
        options: ['Water', 'Tea', 'Milk', 'Rice'], answer: 'Water', translation: 'पानी — Water' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मलाई _____ मनपर्छ',
        english: 'I like momo', answer: 'मोमो', options: ['मोमो', 'रेल', 'घर', 'ढोका'],
        translation: 'मलाई मोमो मनपर्छ — I like momo' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I drink tea',
        answer: ['म', 'चिया', 'पिउँछु'], wordBank: ['म', 'चिया', 'पिउँछु', 'खान्छु'], translation: 'म चिया पिउँछु — I drink tea' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'यो खाना _____ छ',
        english: 'This food is delicious', answer: 'मिठो', options: ['मिठो', 'पिरो', 'ठूलो', 'रातो'],
        translation: 'यो खाना मिठो छ — This food is delicious' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'भात',
        options: ['Rice', 'Bread', 'Lentils', 'Salt'], answer: 'Rice', translation: 'भात — Cooked rice' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'I am hungry',
        answer: ['मलाई', 'भोक', 'लाग्यो'], wordBank: ['मलाई', 'भोक', 'लाग्यो', 'तिर्खा'], translation: 'मलाई भोक लाग्यो — I am hungry' },
    ],
  },

  /* ───────────── TIER 3 ───────────── */
  {
    id: 'getting-around', tier: 3, reqXp: 100, name: 'Getting Around', emoji: '🚕',
    exercises: [
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'रेल',
        options: ['Train', 'Plane', 'Boat', 'Car'], answer: 'Train', translation: 'रेल — Train' },
      { type: 'BUILD', instruction: 'Build the question', english: 'Where is the bus?',
        answer: ['बस', 'कहाँ', 'छ'], wordBank: ['बस', 'कहाँ', 'छ', 'रेल'], translation: 'बस कहाँ छ? — Where is the bus?' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'म _____ जान्छु',
        english: 'I go to Kathmandu', answer: 'काठमाडौं', options: ['काठमाडौं', 'पानी', 'भात', 'रातो'],
        translation: 'म काठमाडौं जान्छु — I go to Kathmandu' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'Go straight ahead',
        answer: ['सिधा', 'जानुहोस्'], wordBank: ['सिधा', 'जानुहोस्', 'बायाँ'], translation: 'सिधा जानुहोस् — Go straight ahead' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'अस्पताल _____ छ',
        english: 'The hospital is near', answer: 'नजिक', options: ['नजिक', 'टाढा', 'ठूलो', 'हो'],
        translation: 'अस्पताल नजिक छ — The hospital is near' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'बायाँ',
        options: ['Left', 'Right', 'Straight', 'North'], answer: 'Left', translation: 'बायाँ — Left' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I need a taxi',
        answer: ['मलाई', 'ट्याक्सी', 'चाहिन्छ'], wordBank: ['मलाई', 'ट्याक्सी', 'चाहिन्छ', 'बस'], translation: 'मलाई ट्याक्सी चाहिन्छ — I need a taxi' },
    ],
  },
  {
    id: 'time-days', tier: 3, reqXp: 100, name: 'Time & Days', emoji: '🕐',
    exercises: [
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'आज',
        options: ['Today', 'Yesterday', 'Tomorrow', 'Now'], answer: 'Today', translation: 'आज — Today' },
      { type: 'BUILD', instruction: 'Build the question', english: 'What time is it?',
        answer: ['कति', 'बज्यो'], wordBank: ['कति', 'बज्यो', 'कहिले'], translation: 'कति बज्यो? — What time is it?' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'म _____ आउँछु',
        english: 'I will come tomorrow', answer: 'भोलि', options: ['भोलि', 'हिजो', 'घर', 'रातो'],
        translation: 'म भोलि आउँछु — I will come tomorrow' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'Today is Monday',
        answer: ['आज', 'सोमबार', 'हो'], wordBank: ['आज', 'सोमबार', 'हो', 'भोलि'], translation: 'आज सोमबार हो — Today is Monday' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: '_____ बिहान छ',
        english: 'It is morning now', answer: 'अहिले', options: ['अहिले', 'साँझ', 'घर', 'ठूलो'],
        translation: 'अहिले बिहान छ — It is morning now' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'हिजो',
        options: ['Yesterday', 'Today', 'Evening', 'Week'], answer: 'Yesterday', translation: 'हिजो — Yesterday' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'See you in the evening',
        answer: ['साँझमा', 'भेटौंला'], wordBank: ['साँझमा', 'भेटौंला', 'बिहान'], translation: 'साँझमा भेटौंला — See you in the evening' },
    ],
  },
  {
    id: 'shopping', tier: 3, reqXp: 100, name: 'Shopping', emoji: '🛍️',
    exercises: [
      { type: 'BUILD', instruction: 'Build the question', english: 'How much is this?',
        answer: ['यो', 'कति', 'हो'], wordBank: ['यो', 'कति', 'हो', 'त्यो'], translation: 'यो कति हो? — How much is this?' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'महँगो',
        options: ['Expensive', 'Cheap', 'Big', 'Beautiful'], answer: 'Expensive', translation: 'महँगो — Expensive' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'यो धेरै _____ छ',
        english: 'This is too expensive', answer: 'महँगो', options: ['महँगो', 'सस्तो', 'मिठो', 'रातो'],
        translation: 'यो धेरै महँगो छ — This is too expensive' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I want to buy this',
        answer: ['म', 'यो', 'किन्छु'], wordBank: ['म', 'यो', 'किन्छु', 'बेच्छु'], translation: 'म यो किन्छु — I will buy this' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मलाई _____ चाहिन्छ',
        english: 'I need money', answer: 'पैसा', options: ['पैसा', 'पानी', 'घर', 'हो'],
        translation: 'मलाई पैसा चाहिन्छ — I need money' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'सस्तो',
        options: ['Cheap', 'Expensive', 'Heavy', 'New'], answer: 'Cheap', translation: 'सस्तो — Cheap' },
      { type: 'BUILD', instruction: 'Build the phrase', english: 'Please lower the price',
        answer: ['मूल्य', 'घटाउनुहोस्'], wordBank: ['मूल्य', 'घटाउनुहोस्', 'बढाउनुहोस्'], translation: 'मूल्य घटाउनुहोस् — Please lower the price' },
    ],
  },

  /* ───────────── TIER 4 ───────────── */
  {
    id: 'feelings', tier: 4, reqXp: 200, name: 'Feelings', emoji: '😊',
    exercises: [
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'खुसी',
        options: ['Happy', 'Sad', 'Angry', 'Tired'], answer: 'Happy', translation: 'खुसी — Happy' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I am very happy',
        answer: ['म', 'धेरै', 'खुसी', 'छु'], wordBank: ['म', 'धेरै', 'खुसी', 'छु', 'दुःखी'], translation: 'म धेरै खुसी छु — I am very happy' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'म _____ छु',
        english: 'I am tired', answer: 'थकित', options: ['थकित', 'खुसी', 'रातो', 'ठूलो'],
        translation: 'म थकित छु — I am tired' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I am not afraid',
        answer: ['म', 'डराउँदिनँ'], wordBank: ['म', 'डराउँदिनँ', 'डराउँछु'], translation: 'म डराउँदिनँ — I am not afraid' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'उनी _____ छिन्',
        english: 'She is sad', answer: 'दुःखी', options: ['दुःखी', 'खुसी', 'भोक', 'सफा'],
        translation: 'उनी दुःखी छिन् — She is sad' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'रिस',
        options: ['Anger', 'Joy', 'Fear', 'Love'], answer: 'Anger', translation: 'रिस — Anger' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I love you',
        answer: ['म', 'तिमीलाई', 'माया', 'गर्छु'], wordBank: ['म', 'तिमीलाई', 'माया', 'गर्छु', 'छु'], translation: 'म तिमीलाई माया गर्छु — I love you' },
    ],
  },
  {
    id: 'nature', tier: 4, reqXp: 200, name: 'Nature & Nepal', emoji: '🏔️',
    exercises: [
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'हिमाल',
        options: ['Mountain', 'River', 'Forest', 'Sky'], answer: 'Mountain', translation: 'हिमाल — Mountain' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'The mountain is big',
        answer: ['हिमाल', 'ठूलो', 'छ'], wordBank: ['हिमाल', 'ठूलो', 'छ', 'सानो'], translation: 'हिमाल ठूलो छ — The mountain is big' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'नेपालमा धेरै _____ छन्',
        english: 'Nepal has many rivers', answer: 'नदी', options: ['नदी', 'घर', 'रेल', 'पैसा'],
        translation: 'नेपालमा धेरै नदी छन् — Nepal has many rivers' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'The sky is blue',
        answer: ['आकाश', 'निलो', 'छ'], wordBank: ['आकाश', 'निलो', 'छ', 'रातो'], translation: 'आकाश निलो छ — The sky is blue' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: '_____ हरियो छ',
        english: 'The forest is green', answer: 'जंगल', options: ['जंगल', 'आकाश', 'पानी', 'घर'],
        translation: 'जंगल हरियो छ — The forest is green' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'सूर्य',
        options: ['Sun', 'Moon', 'Star', 'Cloud'], answer: 'Sun', translation: 'सूर्य — Sun' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'I love Nepal',
        answer: ['म', 'नेपाललाई', 'माया', 'गर्छु'], wordBank: ['म', 'नेपाललाई', 'माया', 'गर्छु', 'छु'], translation: 'म नेपाललाई माया गर्छु — I love Nepal' },
    ],
  },
  {
    id: 'culture', tier: 4, reqXp: 200, name: 'Culture & Festivals', emoji: '🎉',
    exercises: [
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'दशैं',
        options: ['Dashain festival', 'Wedding', 'Market', 'Temple'], answer: 'Dashain festival', translation: 'दशैं — Dashain, Nepal\'s biggest festival' },
      { type: 'BUILD', instruction: 'Build the greeting', english: 'Happy Dashain',
        answer: ['दशैंको', 'शुभकामना'], wordBank: ['दशैंको', 'शुभकामना', 'तिहार'], translation: 'दशैंको शुभकामना — Happy Dashain' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'हामी _____ मनाउँछौं',
        english: 'We celebrate Tihar', answer: 'तिहार', options: ['तिहार', 'पानी', 'रेल', 'घर'],
        translation: 'हामी तिहार मनाउँछौं — We celebrate Tihar' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'This is our culture',
        answer: ['यो', 'हाम्रो', 'संस्कृति', 'हो'], wordBank: ['यो', 'हाम्रो', 'संस्कृति', 'हो', 'घर'], translation: 'यो हाम्रो संस्कृति हो — This is our culture' },
      { type: 'SELECT', instruction: 'Fill in the blank', prompt: 'मन्दिरमा _____ छ',
        english: 'There is a god in the temple', answer: 'देवता', options: ['देवता', 'पैसा', 'भात', 'रातो'],
        translation: 'मन्दिरमा देवता छ — There is a god in the temple' },
      { type: 'MATCH', instruction: 'What does this mean?', prompt: 'मन्दिर',
        options: ['Temple', 'House', 'School', 'Shop'], answer: 'Temple', translation: 'मन्दिर — Temple' },
      { type: 'BUILD', instruction: 'Build the sentence', english: 'We dance together',
        answer: ['हामी', 'सँगै', 'नाच्छौं'], wordBank: ['हामी', 'सँगै', 'नाच्छौं', 'गाउँछौं'], translation: 'हामी सँगै नाच्छौं — We dance together' },
    ],
  },
];

/* ── Word-of-the-day pool (15 words) ── */
const WOTD_POOL = [
  { dev: 'नमस्ते',   roman: 'namaste',  en: 'Hello / Greetings' },
  { dev: 'धन्यवाद',  roman: 'dhanyabad', en: 'Thank you' },
  { dev: 'पानी',     roman: 'pani',     en: 'Water' },
  { dev: 'माया',     roman: 'maya',     en: 'Love' },
  { dev: 'घर',       roman: 'ghar',     en: 'Home' },
  { dev: 'साथी',     roman: 'saathi',   en: 'Friend' },
  { dev: 'हिमाल',    roman: 'himal',    en: 'Mountain' },
  { dev: 'खुसी',     roman: 'khusi',    en: 'Happy' },
  { dev: 'भात',      roman: 'bhaat',    en: 'Rice' },
  { dev: 'चिया',     roman: 'chiya',    en: 'Tea' },
  { dev: 'किताब',    roman: 'kitaab',   en: 'Book' },
  { dev: 'सपना',     roman: 'sapana',   en: 'Dream' },
  { dev: 'बिहान',    roman: 'bihaana',  en: 'Morning' },
  { dev: 'जून',      roman: 'joon',     en: 'Moon' },
  { dev: 'फूल',      roman: 'phool',    en: 'Flower' },
];
